name: FTP Upload Font JSON

on:
  push:
    paths:
      - 'font/font_list.json'  # sadece bu dosya değişirse çalışır
  workflow_dispatch: # manuel tetikleme için

jobs:
  ftp_upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Upload font_list.json to FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ftpupload.net
          username: if0_36792962
          password: EDgDOydXu6W5VTm
          protocol: ftp
          local-dir: font  # repository içindeki klasör
          server-dir: /   # FTP’de göndermek istediğin dizin
          dry-run: false
